name: "link-saver"

services:
  frontend:
    build:
      context: ./
      dockerFile: ./Containerfile
      args:
        BUN_VERSION: "1-alpine"
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    volumes:
      - ./:/app:z
      - /app/.next
      - /app/node_modules
      - vscode:/root/.vscode-server
    restart: unless-stopped

volumes:
  vscode:
    name: vscode
