name: "linksaver"
services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: "linksaver"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: ../
      dockerfile: Containerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - ../.env.local
    volumes:
      - ../:/app:z
      - next:/app/.next
      - node_modules:/app/node_modules
      - frontend_vscode:/root/.vscode-server
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data:
  next:
  node_modules:
  frontend_vscode:
    name: frontend_vscode
